server:
  port: 8081
spring:
  #覆盖容器中的Bean
  main:
    allow-bean-definition-overriding: true
  #redis配置
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000
  #mybatis配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/salmanage?&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

output: C:/Users/pc/Desktop/









